### ISSUE TITLE
TypeError: unhashable type: 'list'

### ISSUE THREAD

**Issue by yiulau** [Bihaqo/t3f#183] opened 2019-09-05 18:34 UTC
When I run 
```

import numpy as np
import tensorflow as tf
tf.enable_eager_execution()
import t3f

a_dense = np.random.rand(8, 27).astype(np.float32)
a_matrix_tt = t3f.to_tt_matrix(a_dense, shape=((2, 2, 2), (3, 3, 3)), max_tt_rank=4)

```
I got this error:

```
Traceback (most recent call last):
  File "test.py", line 7, in <module>
    a_matrix_tt = t3f.to_tt_matrix(a_dense, shape=((2, 2, 2), (3, 3, 3)), max_tt_rank=4)
  File "/home/yiu/anaconda3/envs/tf112/lib/python3.6/site-packages/t3f/decompositions.py", line 77, in to_tt_matrix
    tt_tens = to_tt_tensor(tens, max_tt_rank, epsilon)
  File "/home/yiu/anaconda3/envs/tf112/lib/python3.6/site-packages/t3f/decompositions.py", line 187, in to_tt_tensor
    return TensorTrain(tt_cores, static_shape, ranks)
  File "/home/yiu/anaconda3/envs/tf112/lib/python3.6/site-packages/t3f/tensor_train.py", line 54, in __init__
    with tf.name_scope("TensorTrain", tt_cores):
  File "/home/yiu/anaconda3/envs/tf112/lib/python3.6/site-packages/tensorflow/python/framework/ops.py", line 5998, in __enter__
    if cache_key in name_scope_cache:
TypeError: unhashable type: 'list'

```

I have tensorflow 1.12 and python 3.6

**Comment by Bihaqo** [comment] 2019-09-08 11:21
Hi, thanks for creating the issue. I tried to reproduce it here, but it seems to work normally: https://colab.research.google.com/drive/1c8Km3-F5bb4XoXtqVvMVIJZdqnDvN8QC

Do you know how to change this example to make it fail?

**Comment by Bihaqo** [comment] 2019-10-23 09:52
Closing for now, feel free to reopen if the issue is still there.

**Closed by Bihaqo** 2019-10-23 09:52 UTC
