### ISSUE TITLE
T3F on convolutional layers

### ISSUE THREAD

**Issue by miladdona** [Bihaqo/t3f#217] opened 2021-08-16 07:29 UTC
Hi,

Is it possible to use T3F library (compressing neural networks) on Convolutional layers?
How?

Thanks.

**Comment by Bihaqo** [comment] 2021-08-25 09:48
This is a duplicate of #198, see there for more details and references to some implementations, but the short answer is no, this is not implemented

**Closed as completed by Bihaqo** 2021-08-25 09:48 UTC
